In [1]:
import numpy as np
import pandas as pd

# Splitting of Array


In [2]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
# Horizontal split
upper, lower = np.hsplit(A, 2)
upper

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [5]:
# Vertical split
left, right = np.vsplit(A, 2)


# Min and Max

In [6]:
B = np.random.randint(10, size = (3,4))
B 

array([[4, 9, 3, 9],
       [9, 5, 4, 8],
       [5, 4, 9, 0]])

In [7]:
B.min()

0

In [8]:
# Minimum of columns
B.min(axis = 0)

array([4, 4, 3, 0])

In [9]:
# Minimum of rows
B.min(axis = 1)

array([3, 4, 0])

In [10]:
# Sum of the whole array
B.sum()

69

In [11]:
# Mean of the whole array
B.mean()

5.75

# Boolean

In [14]:
# how many families whose number of members above 5
np.count_nonzero(B<5)

5

In [13]:
# Or this
np.sum(B<5)

5

In [15]:
# find if any of the family has the number of members above 8
np.any(B>8)

True

In [16]:
# find if all families have the number of members above 2
np.all(B>2)

False

In [19]:
#find how many families in the range 3 and 5
np.sum((B >= 3) & (B <= 5))

6

In [22]:
# find the number of families that are not less than 3 or above 5
np.sum(~(B < 3) | (B > 5))

11

In [24]:
#Peek at what numbers are above 5 in our data
B[B > 5]

array([9, 9, 9, 8, 9])

# Sorting

# Sort indices

In [26]:
x = np.array([3, 1, 2, 4, 6])
np.sort(x)

array([1, 2, 3, 4, 6])

In [27]:
# Sort indices
indices = np.argsort(x)
indices

array([1, 2, 0, 3, 4])

## Sort Columns or Rows

In [28]:
A = np.random.randint(0, 10, (4, 6))

In [29]:
# By columns
np.sort(A, axis=0)

array([[3, 0, 5, 3, 2, 2],
       [4, 1, 6, 5, 3, 3],
       [6, 2, 8, 7, 6, 9],
       [7, 6, 9, 8, 7, 9]])

In [30]:
# By rows
np.sort(A, axis=1)

array([[1, 3, 5, 6, 7, 9],
       [2, 3, 6, 7, 8, 9],
       [3, 4, 5, 6, 7, 9],
       [0, 2, 2, 3, 6, 8]])