In [1]:
import numpy as np

# Array

In [2]:
#Create an array with specific data type
#Pass a list, nested list, tuple
np.array([1,2,3], dtype=np.uint)

array([1, 2, 3], dtype=uint64)

In [3]:
#Create an array with boolean
np.array([1,0,1,0], dtype=np.bool)

array([ True, False,  True, False])

In [4]:
#Create an array with specific range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Specify the range and how big the step is
np.arange(2,100, 5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [6]:
#Create an array in specific range with specific number of elements
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Matrix

In [7]:
#Create an empty matrix
np.empty((3,3))

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667],
       [0.77777778, 0.88888889, 1.        ]])

In [8]:
#Create an array with 0 elements
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#Create the matrix filled with specified elements
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [11]:
#Create an identity matrix with dimension 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Create a diagonal matrix with diagonal elements specified in the array x
x = [1,2,3]
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
#Create a matrix with random elements between 0 and 1
np.random.random((3,3))

array([[0.08072316, 0.1017695 , 0.06957811],
       [0.54207022, 0.57382342, 0.13976722],
       [0.97999045, 0.95309606, 0.69654229]])

In [15]:
#Create a matrix with random float elements with a specific range
np.random.normal(0, 10, (3,3))

array([[-14.30395273,  -2.59601277,  -3.02542053],
       [ -3.58543771,  -5.60373287,  -3.25726778],
       [ -4.35590817,  -8.09567952,  13.89164511]])

In [16]:
#Create a matrix with random integer elements with a specific range
np.random.randint(0,10, (3,3))

array([[9, 5, 3],
       [0, 5, 7],
       [7, 2, 2]])

In [17]:
#Create the matrix with the same dimension but different elements
A = np.zeros((10,10))
B = np.ones_like(A)
B

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Operations on matrices

In [23]:
A = np.array([[1, 1, 1], [2, 2, 2]], dtype= np.float64)
B = np.array([[1, 3, 4], [3, 2, 1]], dtype= np.float64)

#Pointwise addition and multiplication
A + B
A * B

array([[1., 3., 4.],
       [6., 4., 2.]])

In [24]:
C = np.array([1,2,3], dtype = np.float64)

#Matrix multiplication
#Make sure the dimension of A is mxn and dimension of C is nxp
A@ C

array([ 6., 12.])

In [25]:
#Matrix multiplication alternative
np.dot(A, C)

array([ 6., 12.])

In [26]:
#Find the transpose of a matrix
#Transpose: Columns become rows and rows become columns
A.T

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [27]:
#reshape the array
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#Return the sum along the diagonals of the array
np.trace(A)

3.0

In [29]:
# a.T * y (1xn * nx1)
a = np.arange(5)
b = np.arange(5)


#this returns a scaler
np.dot(a,b)

30

In [30]:
# a * y.T  (nx1 * 1*n)
#this returns a matrix nxn
np.outer(a,b)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [31]:
#Use boolean to return a specific row
A[[True, False],]

array([[1., 1., 1.]])

In [32]:
#Or column
A[:, [True, False, False]]

array([[1.],
       [2.]])

# Linear Algebra

In [33]:
#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:


a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [34]:
#Compute the inverse of a matrix
np.linalg.pinv(A)

array([[0.06666667, 0.13333333],
       [0.06666667, 0.13333333],
       [0.06666667, 0.13333333]])

In [35]:
#Return matrix norm
np.linalg.norm(A)

3.872983346207417

In [36]:
#Single Value Decomposition

U, S, V = np.linalg.svd(A)

U 

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

In [37]:
A = np.arange(9).reshape(3,3)

#Find eigenvalues on square matrix
np.linalg.eig(A)


(array([ 1.33484692e+01, -1.34846923e+00, -1.15433316e-15]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

# Common Method for Data Science

In [38]:
#Flatten a matrix by row
A.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
#Flatten a matrix by column
A = A.flatten(order='F')
A 

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [40]:
#Reshape the flattened matrix
A = A.reshape((3,3))
A 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [41]:
#Change the type of the elements
A.astype(np.float64) 

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.]])

In [42]:
#Create a copy of A
newA = np.copy(A)
newA 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [44]:
B = np.array([[1, 3],
             [4, 3],
             [2, 1]])

In [45]:
#Add the matrix B to columns of matrix A 
np.concatenate([A,B], axis = 1) 

array([[0, 3, 6, 1, 3],
       [1, 4, 7, 4, 3],
       [2, 5, 8, 2, 1]])

In [46]:
#Add the matrix B to rows of matrix A 
np.concatenate([A,B.reshape(2, 3)], axis = 0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [1, 3, 4],
       [3, 2, 1]])

In [47]:
#Create a copy of A with every entry in the matrix, the lowest is 0 and highest is 5
#The element that does not satisfy the condition will become the lowest or highest value
np.clip(A, 0.0, 5)

array([[0., 3., 5.],
       [1., 4., 5.],
       [2., 5., 5.]])

In [48]:
#Add the elements in the same row to create a new vector
np.sum(A, axis = 1) 

array([ 9, 12, 15])

In [49]:
#Take the average the elements in the same row to create a new vector
np.average(A, axis = 1)

array([3., 4., 5.])

In [51]:
x = np.arange(10)

In [52]:
#Shuffle the elements in the array
np.random.shuffle(x)

In [53]:
x 

array([2, 7, 6, 4, 5, 0, 3, 9, 8, 1])

In [54]:
#Or matrix
np.random.shuffle(A)
A


array([[1, 4, 7],
       [2, 5, 8],
       [0, 3, 6]])